### PR TITLE
Adding list variables to the template

### PR DESCRIPTION
**Pull request by AlexandreMarcq**
Using `#`, it is possible to declare a list, for example `#{listVar}`:

image

When prompted to replace data, a text area is given with a button to choose wether the list should be ordered or unordered:

image

By default, this:

image

Will turn into this:

image

And this:

image

Into this:

image

### CODE REVIEW

**Comment by AlexandreMarcq** [comment]
Before merging @barrydegraaff , could you check that this deploys correctly? I can't seem to deplot it on my test server unless it's either in the `_dev` folder or I use `?dev=1`. I didn't change much in the configuration files, I don't get why the Javascript doesn't get generated in production mode.

**Comment by barrydegraaff** [comment]
Hello Alexandre,

If you have issues that something works in development mode but not when 
deployed in production, it is most likely you made a syntax error that 
chokes yuicompressor, which is used for cache optimization.


You can find out what line of code is giving the issue by using this 
command:


java -jar yuicompressor-2.4.8.jar "/path/to/your-zimlet/javascript.js"


Please let me know if that helps!

**Comment by AlexandreMarcq** [comment]
This command gives me a syntax error at line 565, which is this one:
```javascript
var list = "<" + type + ">" + val.split('\n').map(x => "<li>" + x + "</li>").join("") + "</" + type + ">";
```
I don't see anything wrong with it, maybe the `map` syntax is giving the problem?

**Comment by barrydegraaff** [comment]
Yes yuicompressor does not seem to understand it, so you have to rewrite your code so it does

**Comment by AlexandreMarcq** [comment]
This works now (see updated initial comment), it is readu to be merged.

**Pull request merged**
